# BEHAVIOUR TREE PARAMS

bt_navigator:
  ros__parameters:
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    bt_loop_duration: 10
    default_server_timeout: 20
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_compute_path_through_poses_action_bt_node
      - nav2_smooth_path_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_drive_on_heading_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_globally_updated_goal_condition_bt_node
      - nav2_is_path_valid_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_reinitialize_global_localization_service_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_truncate_path_local_action_bt_node
      - nav2_goal_updater_node_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_path_expiring_timer_condition
      - nav2_distance_traveled_condition_bt_node
      - nav2_single_trigger_bt_node
      - nav2_goal_updated_controller_bt_node
      - nav2_navigate_through_poses_action_bt_node
      - nav2_navigate_to_pose_action_bt_node
      - nav2_remove_passed_goals_action_bt_node
      - nav2_planner_selector_bt_node
      - nav2_controller_selector_bt_node
      - nav2_goal_checker_selector_bt_node
      - nav2_controller_cancel_bt_node
      - nav2_path_longer_on_approach_bt_node
      - nav2_wait_cancel_bt_node
      - nav2_spin_cancel_bt_node
      - nav2_back_up_cancel_bt_node
      - nav2_drive_on_heading_cancel_bt_node

bt_navigator_navigate_through_poses_rclcpp_node:
  ros__parameters:
    use_sim_time: False

bt_navigator_navigate_to_pose_rclcpp_node:
  ros__parameters:
    use_sim_time: False

global_costmap:
  global_costmap:
    ros__parameters:
      always_send_full_costmap: True
      global_frame: map
      lethal_cost_threshold: 254
      map_topic: /map
      publish_frequency: 3.0
      update_frequency: 3.0
      resolution: 0.03
      robot_base_frame: base_link
      robot_radius: 0.14 
      track_unknown_space: true
      
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        subscribe_to_updates: True
        map_subscribe_transient_local: True
        map_topic: /map
      
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        max_obstacle_height: 0.3
        combination_method: 1
        observation_sources: scan
        scan:
          topic: /scan
          sensor_frame: lidar_frame
          observation_persistance: 0.0
          expected_update_rate: 6.5
          data_type: "LaserScan"
          min_obstacle_height: 0.0
          max_obstacle_height: 0.3
          inf_is_valid: False
          marking: True
          clearing: True
          obstacle_max_range: 5.0
          obstacle_min_range: 0.5
          raytrace_max_range: 6.0
          raytrace_min_range: 0.5
     
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.40
        cost_scaling_factor: 5.0
        inflate_unknown: False
        inflate_around_unknown: False

local_costmap:
  local_costmap:
    ros__parameters:
      always_send_full_costmap: True
      global_frame: odom
      lethal_cost_threshold: 254
      update_frequency: 7.0
      publish_frequency: 5.0
      resolution: 0.03
      robot_base_frame: base_link
      rolling_window: True
      width: 3
      height: 3
      robot_radius: 0.14
      track_unknown_space: True

      plugins: ["obstacle_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 5.0
        inflation_radius: 0.20
        inflate_unknown: False
        inflate_around_unknown: False

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        max_obstacle_height: 0.3
        combination_method: 1
        observation_sources: scan
        scan:
          topic: /scan
          sensor_frame: lidar_frame
          observation_persistance: 0.0
          expected_update_rate: 6.5
          data_type: "LaserScan"
          min_obstacle_height: 0.0
          max_obstacle_height: 0.3
          inf_is_valid: False
          marking: True
          clearing: True
          obstacle_max_range: 4.0
          obstacle_min_range: 0.1
          raytrace_max_range: 5.0
          raytrace_min_range: 0.1
     
planner_server:
  ros__parameters:
    expected_planner_frequency: 1.5
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.1
      use_astar: True
      allow_unknown: True

controller_server:
  ros__parameters:
    controller_frequency: 10.0
    use_realtime_priority: True
    controller_plugins: ["FollowPath"]
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["goal_checker"] 
    min_x_velocity_threshold: 0.005
    min_y_velocity_threshold: 0.005
    min_theta_velocity_threshold: 0.005
    failure_tolerance: 0.5
    odom_topic: /odom

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.3
      movement_time_allowance: 10.0

    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.12
      yaw_goal_tolerance: 0.25
      stateful: True

    FollowPath:
      plugin: "nav2_rotation_shim_controller::RotationShimController"
      primary_controller: "dwb_core::DWBLocalPlanner"
      angular_dist_threshold: 0.523599
      forward_sampling_distance: 0.5
      rotate_to_heading_angular_vel: 0.07
      max_angular_accel: 0.15
      simulate_ahead_time: 2.0
      
      # Critics
      critics: ["BaseObstacle",  "GoalAlign", "GoalDist", "Oscillation", "PathAlign", "PathDist", "RotateToGoal"]
      prune_plan: true
      shorten_transformed_plan: true
      prune_distance: 0.2
      forward_prune_distance: 0.5
      debug_trajectory_details: True
      transform_tolerance: 0.2
      short_circuit_trajectory_evaluation: true

      BaseObstacle.scale: 1.0
      
      # After making sure everything work nerf the goal align critic
      GoalAlign.forward_point_distance: 0.40
      GoalAlign.scale: 16.0
      GoalDist.scale: 22.0

      # Only rotate robot when its close to goal
      xy_goal_tolerance: 0.15
      trans_stopped_velocity: 0.25
      RotateToGoal.slowing_factor: 5.0
      RotateToGoal.lookahead_time: -1.0
      RotateToGoal.scale: 14.0
      
      PathAlign.forward_point_distance: 0.60
      PathAlign.scale: 10.0
      PathDist.scale: 10.0
      
      # Kinematic Params
      max_vel_y: 0.0
      min_vel_y: 0.0
      acc_lim_y: 0.0
      decel_lim_y: 0.0

      min_vel_x: -0.012
      max_vel_x: 0.012

      min_speed_xy: -0.012
      max_speed_xy: 0.012

      decel_lim_x: -0.1
      acc_lim_x: 0.1

      min_speed_theta: -0.06
      max_vel_theta: 0.06
      
      decel_lim_theta: -0.1
      acc_lim_theta: 0.1      
      
      # Iterator Params
      vx_samples: 35
      vy_samples: 5
      vtheta_samples: 35

      # Trajectory Generator Params
      sim_time: 2.5
      discretize_by_time: False
      linear_granularity: 0.05
      angular_granularity: 0.05
      include_last_point: True
     

map_server:
  ros__parameters:
    yaml_filename: "/home/glados/mnt/glados_ws/us_room.yaml"
    topic_name: /map
    frame_id: map

map_saver:
  ros__parameters:
    save_map_timeout: 5.0
    free_thresh_default: 0.10
    occupied_thresh_default: 0.90
    map_subscribe_transient_local: True

amcl:
  ros__parameters:
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 12.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 2500
    min_particles: 1000
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: True
    transform_tolerance: 1.0
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: scan

behavior_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
    wait:
      plugin: "nav2_behaviors/Wait"
    global_frame: odom
    robot_base_frame: base_link
    transform_tolerance: 0.1
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

smoother_server:
  ros__parameters:
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      do_refinement: True
      refinement_num: 3
    
velocity_smoother:
  ros__parameters:
    use_realtime_priority: True
    smoothing_frequency: 30.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [0.012, 0.0, 0.06]
    min_velocity: [-0.012, 0.0, -0.06]
    max_accel: [0.10, 0.0, 0.10]
    max_decel: [-0.10, 0.0, -0.10]
    odom_topic: "odom"
    odom_duration: 0.1
    deadband_velocity: [0.002, 0.0, 0.0]
    velocity_timeout: 1.0

waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200