teleop_twist_joy_node:
  ros__parameters:
    
    axis_linear:  # Left thumb stick vertical
      x: 1
    scale_linear:
      x: 0.01015
    scale_linear_turbo:
      x: 0.0154
    
    axis_angular:  # Left thumb stick horizontal
      yaw: 2
    scale_angular:
      yaw: 0.058496
    scale_angular_turbo:
      yaw: 0.1715877

    enable_button: 5  # RB 
    enable_turbo_button: 0 # A

    inverted_reverse: true